### ISSUE TITLE
チャットにて送信時に困った点（スマホ）

### ISSUE THREAD

**Issue by Goi666** [eRy-sk/teamup_app#22]
※iPhoneを使用しての書き込み時になります。

チャットにて書き込み後、送信ボタンがなく困りました。
デフォルトのキーボードにある「改行」で送信されました。
この場合、スマホだと改行ができなくなるかと思います。

PCだとshift + enterで改行はよくあるパターンですが
スマホだとそのような機能はないため少し気になりました。

**Comment by eRy-sk** [comment]
現状改行ができないのは仕様です。ですがやはり改行できた方がいいですよね...。
#7 で対応予定です。フィードバックありがとうございます。
